package com.dk.colorgame.enums;

/**
 * Created by Dawid Kotarba on 2015-04-29.
 */
public enum GameStateEnum {
    MENU_MAIN, MENU_RECORDS, MENU_SCORE_RESET, MENU_GAME_OVER, MENU_SCORES, MENU_OPTIONS, MENU_OPTIONS_VIDEO, MENU_OPTIONS_AUDIO, MENU_OPTIONS_GAME, MENU_CREDITS, PAUSED, STARTED
}
